name: Deploy Star battle to production

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: List repository files
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Battleship.sln
      
    - name: Build .NET app
      run: dotnet build --configuration release --no-restore
      
    - name: Build .NET app
      run: dotnet publish --configuration release -r ubuntu.22.04-x64 --self-contained true
      
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    - name: Build Docker image
      run: docker build -t game-server:${{ github.sha }} .

    - name: Install and setup rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

    - name: Transfer Docker image to DigitalOcean instance
      run: |
        docker save game-server:${{ github.sha }} | gzip > game-server.tar.gz
        rsync -e "ssh -i private_key -o StrictHostKeyChecking=no" -avz --progress game-server.tar.gz root@167.172.102.146:/tmp

    - name: Deploy to DigitalOcean
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no root@167.172.102.146> "docker load < /tmp/game-server.tar.gz"
        ssh -i private_key -o StrictHostKeyChecking=no root@167.172.102.146> "docker stop game-server || true && docker rm game-server || true"
        ssh -i private_key -o StrictHostKeyChecking=no root@167.172.102.146> "docker run -d -p 80:80 --name game-server game-server:${{ github.sha }}"
